root_route_redirect:
  path: /
  methods: [ GET ]
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: '/resume'
        
create-resume:
  path: /resume
  methods: [ GET ]
  controller: App\Controller\MainController::createResume
