root_route_redirect:
  path: /
  methods: [ GET ]
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: '/resume'

resume-index:
  path: /resume
  methods: [ GET, POST ]
  controller: App\Controller\MainController::index

create-resume:
  path: /resume/new
  methods: [ GET, POST ]
  controller: App\Controller\MainController::createResume

edit-resume:
  path: /resume/{ulid}/edit
  methods: [ GET, POST ]
  controller: App\Controller\MainController::editResume

delete-resume:
  path: /resume/{ulid}/delete
  methods: [ GET, POST ]
  controller: App\Controller\MainController::deleteResume

pdfs-index:
  path: /pdfs
  methods: [ GET ]
  controller: App\Controller\MainController::getPdfs

delete-pdf:
  path: /pdfs/{filename}/delete
  methods: [ GET, POST ]
  controller: App\Controller\MainController::deletePdf