root_route_redirect:
  path: /
  methods: [ GET ]
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: '/resumes'

get-all-resumes:
  path: /resumes
  methods: [ GET, POST ]
  controller: App\Controller\MainController::getAllResumes

create-resume:
  path: /resumes/new
  methods: [ GET, POST ]
  controller: App\Controller\MainController::createResume

edit-resume:
  path: /resumes/{ulid}/edit
  methods: [ GET, POST ]
  controller: App\Controller\MainController::editResume

delete-resume:
  path: /resumes/{ulid}/delete
  methods: [ GET, POST ]
  controller: App\Controller\MainController::deleteResume

get-all-pdfs:
  path: /pdfs
  methods: [ GET ]
  controller: App\Controller\PDFController::getAllPdfs

delete-pdf:
  path: /pdfs/{filename}/delete
  methods: [ GET, POST ]
  controller: App\Controller\PDFController::deletePdf

delete-all-pdfs:
  path: /pdfs/delete-all
  methods: [ GET, POST ]
  controller: App\Controller\PDFController::deleteAllPdfs